name: my-first-action
run-name: Setting up Node
runs:
  using: "composite"
  steps:
    - name: My second step - installing node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: node --v
    - shell: bash