name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: scripts
            shell: bash
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4
      - name: My second step - installing node
        uses: ./.github/actions/my-first-action
      - name: My third step - running the scripts
        run: bash ./my-script.sh
      - run: npm install -g bats
      - run: bats -v
