name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    # branches:
    #   - main
    tags:
      - 'v*'
  pull_request:

# concurrency (only 1 workflow can run in a group at one time)

jobs:
  # job1-check-bats-version:
  # needs (specify what jobs needs to be complete first before running this job)

  # if ${ { always() } }
  # In this case always() makes it so that this job will always run no matter what
  # If makes it so that this job it is under will run if the condition evaluates to true

    # name: My first job
    # runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     version: [10, 12, 14]
    #     os: [macOs, windows, ubuntu-latest]
    # note: runs (variable.length multipled together) # of threads
    # This will create 3 threads, each running with different version, assuming you
    # are using the version values

    # defaults:
    #     run:
    #         working-directory: .github/scripts
    #         shell: bash
    # steps:
    #   - name: My first step - check out repository
    #     uses: actions/checkout@v4

    #   - name: My second step - installing node
    #     uses: ./.github/actions/my-first-action

    #   - name: Make the script files executable
    #     run: chmod +x my-script.sh

    #   - name: My third step - running the scripts
    #     run: ./my-script.sh
        
    #   - run: npm install -g bats
    #   - run: bats -v

  build:
    name: Relase Product
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"
      - name: Use the value
        id: step_two
        run: |
          printf '%s\n' "$action_state" # This will output 'yellow'
        

      # - name: Create release
      #   id: create_release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ github.ref_name }}
      #   run: |
      #     gh release create "$tag" \
      #         --repo="$GITHUB_REPOSITORY" \
      #         --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
      #         -n "First actual release test 2"
